[package]
name = "mock-desktop-portfolio"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys = "0.3.106"
leptos = { version = "0.8.22", features = ["csr"] }
web-sys = { version = "0.3.106", features = ["Window", "Document", "PointerEvent", "HtmlElement", "Element"] }

[build-dependencies]
pest = "2.9.2"
pest_derive = "2.9.2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
